Диплом
ElenaLut/java-explore-with-me pull request #1
Opened 2022-10-27 21:39 UTC by ElenaLut

2022-10-30 20:24 UTC, Frilock requested changes
Добрый вечер, оставил ряд комментариев к работе, жду новую итерацию. Будут вопросы приходите

2022-10-30 20:24 UTC, Frilock commented on README.md
> +https://github.com/ElenaLut/java-explore-with-me/pull/1
Знаю, что по ТЗ у Вас сказано, чтобы в Readme файле была ссылка на проект. Предлагаю также в данном файле разместить информацию о самом проекте, за что каждый модуль отвечает, как проект собирается. Чтобы стороннему человеку который видит Ваш проект было проще. Кроме того, можно описать специфические конфиг файлы, если они есть. Это хорошая практика.

2022-10-30 20:24 UTC, Frilock commented on README.md
>  Template repository for ExploreWithMe project.
Давайте объединим коммиты (сделайте squash), поскольку они не все имеют какую то осмысленную идею

2022-10-30 20:24 UTC, Frilock commented on pom.xml
> +				<version>42.5.0</version>
Версии библиотек правильнее указывать в одном месте, а именно, в properties, чтобы при смене версии не приходилось лазить по иногда большому pom файлу.

2022-10-30 20:24 UTC, Frilock commented on server/src/main/java/ru/practicum/explorewithme/category/CategoryAdminController.java
> +@Slf4j
Лишняя аннотация

2022-10-30 20:24 UTC, Frilock commented on server/src/main/java/ru/practicum/explorewithme/category/CategoryAdminServiceImpl.java
> +        if (categoryUpdate.getName().equals(category.getName())) {
А categoryUpdate.getName() null не вернет?

2022-10-30 20:24 UTC, Frilock commented on server/src/main/java/ru/practicum/explorewithme/category/CategoryPublicController.java
> +@Slf4j
По моему лишняя аннотация, проверьте в других местах пожалуйста

2022-10-30 20:24 UTC, Frilock commented on server/src/main/java/ru/practicum/explorewithme/category/CategoryRepository.java
> +@Repository
Данная аннотация не нужна, над интерфейсами нет смысла ставить аннотация для спринговых бинов, нужно ставить над реализацией

2022-10-30 20:24 UTC, Frilock commented on server/src/main/java/ru/practicum/explorewithme/category/model/Category.java
> +    @Column(name = "name")
Смотрите, вы в своих скриптах для полей указываете так же размер и различные флаги, например, not null, нужно это все дублировать в аннотации column, чтобы не приходилось вечно лазить в скрипты и искать, например, чему может быть равно поле

2022-10-30 20:24 UTC, Frilock commented on server/src/main/java/ru/practicum/explorewithme/compilation/CompilationAdminController.java
> +@Slf4j
Лишняя аннотация

2022-10-30 20:24 UTC, Frilock commented on server/src/main/java/ru/practicum/explorewithme/compilation/CompilationAdminServiceImpl.java
> +@Transactional(readOnly = true)
А  в чем смысл на класс вешать транзакция, а также на все другие методы? Можете пояснить, интересен Ваш ответ

2022-10-30 20:24 UTC, Frilock commented on server/src/main/java/ru/practicum/explorewithme/compilation/CompilationPublicServiceImpl.java
> +@Transactional(readOnly = true)
А в чем смысл вешать транзакцию на методы сервиса, если вы уже повесили ее на методах контроллера выше? Нужно как то с этим разобраться...

2022-10-30 20:24 UTC, Frilock commented on server/src/main/java/ru/practicum/explorewithme/compilation/CompilationRepository.java
> +    @Query("update Compilation as c " +
У Вас в одном месте SELECT, в другом update - давайте приведем к одному формату, Вы либо все большими пишите, либо все строчными

2022-10-30 20:24 UTC, Frilock commented on server/src/main/java/ru/practicum/explorewithme/event/EventAdminServiceImpl.java
> +    public List<EventFullDto> getEventsByAdmin(List<Long> users, List<String> states, List<Long> categories, LocalDateTime start, LocalDateTime end, int from, int size) {
Слишком длинная строка, давайте аргументы переносить на новую, т.е.
users,
states,
....

2022-10-30 20:24 UTC, Frilock commented on server/src/main/java/ru/practicum/explorewithme/event/EventAdminServiceImpl.java
> +        if (adminUpdateEventRequest.getEventDate() != null) {
Данную конструкцию можно заменить на Optional.ofNullable(adminUpdateEventRequest.getCategory()).ifPresent(event::setDescription);
ну что то такое, будет выглядеть компактнее

2022-10-30 20:24 UTC, Frilock commented on server/src/main/java/ru/practicum/explorewithme/event/EventAdminServiceImpl.java
> +        if (!event.getState().equals(EventState.PENDING)) {
enum поля правильнее сравнивать через стандартные операторы != и ==, работать будет в любом случае, но стандартные операторы как минимум быстрее

2022-10-30 20:24 UTC, Frilock commented on server/src/main/java/ru/practicum/explorewithme/event/EventAdminServiceImpl.java
> +            log.error("Собитие {} начинается менее чем через час", event.getId());
Опечатка в слове Событие

2022-10-30 20:24 UTC, Frilock commented on server/src/main/java/ru/practicum/explorewithme/event/EventAdminServiceImpl.java
> +        if (event.getEventDate().isBefore(LocalDateTime.now().plusHours(1))) {
event.getEventDate() null не вернет?

2022-10-30 20:24 UTC, Frilock commented on server/src/main/java/ru/practicum/explorewithme/user/UserAdminServiceImpl.java
> +        if (id == null) {
Данную конструкцию можно заменить на другую, с использованием тернарного оператора. Будет выглядеть компактнее

2022-10-30 20:24 UTC, Frilock commented on server/src/main/java/ru/practicum/explorewithme/user/model/User.java
> +package ru.practicum.explorewithme.user.model;
Знаю, что в ТЗ у Вас это было задание со звездочкой, но вообще в такой большой работе, хочется увидеть unit тесты, которые тестируют хотя бы сервисы, поскольку это поможет Вам отловить возможные ошибки, а сама работа будет выглядеть солиднее

2022-10-31 21:42 UTC, ElenaLut commented on README.md
>  Template repository for ExploreWithMe project.
Удалила все попытки тестовые

2022-10-31 22:19 UTC, ElenaLut commented on server/src/main/java/ru/practicum/explorewithme/category/CategoryAdminController.java
> +@Slf4j
Во всех контроллерах поправила

2022-10-31 22:21 UTC, ElenaLut commented on server/src/main/java/ru/practicum/explorewithme/category/CategoryAdminServiceImpl.java
> +        if (categoryUpdate.getName().equals(category.getName())) {
добавила проверку

2022-10-31 22:25 UTC, ElenaLut commented on server/src/main/java/ru/practicum/explorewithme/event/EventAdminServiceImpl.java
> +        if (!event.getState().equals(EventState.PENDING)) {
Поправила во всех enum

2022-10-31 22:27 UTC, ElenaLut commented on server/src/main/java/ru/practicum/explorewithme/category/CategoryPublicController.java
> +@Slf4j
Во всех контроллерах поправила

2022-10-31 22:30 UTC, ElenaLut commented on server/src/main/java/ru/practicum/explorewithme/category/CategoryRepository.java
> +@Repository
убрала во всех репозиториях

2022-10-31 22:49 UTC, ElenaLut commented on server/src/main/java/ru/practicum/explorewithme/category/model/Category.java
> +    @Column(name = "name")
Добавила в моделях

2022-10-31 22:53 UTC, ElenaLut commented on server/src/main/java/ru/practicum/explorewithme/compilation/CompilationRepository.java
> +    @Query("update Compilation as c " +
перевела все на строчные

2022-10-31 22:59 UTC, ElenaLut commented on server/src/main/java/ru/practicum/explorewithme/event/EventAdminServiceImpl.java
> +    public List<EventFullDto> getEventsByAdmin(List<Long> users, List<String> states, List<Long> categories, LocalDateTime start, LocalDateTime end, int from, int size) {
во всех классах поправила, где длинные строки были

2022-10-31 23:13 UTC, ElenaLut commented on server/src/main/java/ru/practicum/explorewithme/compilation/CompilationAdminServiceImpl.java
> +@Transactional(readOnly = true)
Пока чинила код, не могула разобраться с ошибками - не удалялись подборки. На форумах прочитала, что может помочь аннотация транзакции - помогло. Забыла удалить лишние. Сейчас поправила

2022-11-01 15:40 UTC, ElenaLut commented on server/src/main/java/ru/practicum/explorewithme/user/UserAdminServiceImpl.java
> +        if (id == null) {
Спасибо! Не додумалась так делать, гораздо удобнее!

2022-11-01 22:47 UTC, ElenaLut commented on server/src/main/java/ru/practicum/explorewithme/user/model/User.java
> +package ru.practicum.explorewithme.user.model;
Я собиралась добавить тесты, но переживаю, что не успею сделать фичу до дедлайна. Если можно, я бы сначала занялась ей. Потом перешла к написанию тестов

2022-11-02 14:55 UTC, Frilock requested changes
Добрый вечер, еще немного комментариев к работе

2022-11-02 14:55 UTC, Frilock commented on pom.xml
> +		<org.springframework.boot.version>2.7.4</org.springframework.boot.version>
Префиксы org, com и т.д. Вы можете не добавлять в название версии, главное чтоб было понятно что за библиотека

2022-11-02 14:55 UTC, Frilock commented on server/src/main/java/ru/practicum/explorewithme/category/CategoryAdminServiceImpl.java
> +        if (categoryUpdate.getName().equals(category.getName()) && category.getName() != null) {
не очень нравится такая проверка, точнее не совсем понял суть, то есть category.getName() != null - мб равен null, а categoryUpdate.getName() тоже соответственно может? 
Следовательно, может возникнуть ошибка. Чтобы вечно не думать, а может быть поле null или нет, предлагаю использовать null safe equals. Objects.equals(o1, o2)

2022-11-02 14:55 UTC, Frilock commented on server/src/main/java/ru/practicum/explorewithme/event/EventAdminServiceImpl.java
> +        Optional.ofNullable(adminUpdateEventRequest.getRequestModeration()).ifPresent(event::setRequestModeration);
Дублируется строчка

2022-11-02 14:55 UTC, Frilock commented on server/src/main/java/ru/practicum/explorewithme/event/EventAdminServiceImpl.java
> +        if (event.getEventDate().isBefore(LocalDateTime.now().plusHours(1)) && event.getEventDate() != null) {
Смотрите, вот в условиях в коде, они проверяются слева на право, то есть вот вы добавили проверку event.getEventDate() != null, а она вам не поможет, поскольку она идет после первой, где может возникнуть NPE. Поправьте в других местах тоже (если есть)

2022-11-02 14:55 UTC, Frilock commented on server/src/main/java/ru/practicum/explorewithme/event/EventPrivateServiceImpl.java
> +        if (updateEventRequestDto.getParticipantLimit() != null) {
А почему тут на Optional менять не стали? Вроде тоже можно

2022-11-02 14:55 UTC, Frilock commented on server/src/main/java/ru/practicum/explorewithme/event/EventPublicServiceImpl.java
> +            if (sort.equals("EVENT_DATE")) {
Давайте значения сортировок вынесем в enum и тут его будем использовать

2022-11-02 14:55 UTC, Frilock commented on server/src/main/java/ru/practicum/explorewithme/exception/ErrorHandler.java
> +    public ResponseEntity<String> uncaughtException(Throwable e) {
А этот метод точно нужен публичным? по гиту не могу понять

2022-11-02 14:55 UTC, Frilock commented on server/src/main/resources/schema.sql
> +    ANNOTATION VARCHAR(2000)                     NOT NULL,
немного форматирование сьехало

2022-11-03 21:31 UTC, ElenaLut commented on server/src/main/java/ru/practicum/explorewithme/event/EventAdminServiceImpl.java
> +        if (event.getEventDate().isBefore(LocalDateTime.now().plusHours(1)) && event.getEventDate() != null) {
Поправила во всех классах

2022-11-03 21:34 UTC, ElenaLut commented on server/src/main/java/ru/practicum/explorewithme/event/EventPrivateServiceImpl.java
> +        if (updateEventRequestDto.getParticipantLimit() != null) {
Проглядела, изменила сейчас

2022-11-03 21:52 UTC, ElenaLut commented on server/src/main/java/ru/practicum/explorewithme/category/CategoryAdminServiceImpl.java
> +        if (categoryUpdate.getName().equals(category.getName()) && category.getName() != null) {
Спасибо! Так удобнее, буду пользоваться

2022-11-03 21:57 UTC, ElenaLut commented on server/src/main/java/ru/practicum/explorewithme/exception/ErrorHandler.java
> +    public ResponseEntity<String> uncaughtException(Throwable e) {
Прошу прощения, я делала копипаст эксепшенов с прошлого проекта. Этот метод не нужен тут. Удалила

2022-11-04 20:05 UTC, Frilock approved these changes
Работу принял, успехов в дальнейшем!

2022-11-05 20:49 UTC, merged